version: '3'
services:

  postgis:
    image: postgis/postgis:10-2.5
    environment:
      - POSTGRES_DB=datacube
      - POSTGRES_USER=datacube
      - POSTGRES_PASSWORD=datacube
    volumes:
      - postgis-db-volume:/var/lib/postgresql/data
    restart: always

  jupyter:
    image: donaurelio/datacube:1.8.2-ubuntu-20.04
    environment:
      - PATH=$PATH:/home/datacube/.local/bin
      # open data cube specific variables
      - DB_DATABASE=datacube 
      - DB_HOSTNAME=postgis 
      - DB_USERNAME=datacube 
      - DB_PASSWORD=datacube 
    volumes:
      - /vagrant:/vagrant
    command: bash -c "cd /vagrant && jupyter-lab --no-browser --LabApp.token='' --port=8081 --ip=0.0.0.0 --allow-root"
    ports:
      - 8081:8081
    restart: always

volumes:
  postgis-db-volume:
